# Generated by Django 2.1 on 2018-08-21 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creattime', models.TimeField(auto_created='NOW')),
                ('applynum', models.CharField(max_length=32)),
                ('applyname', models.CharField(max_length=32)),
                ('applytext', models.TextField()),
                ('check', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnum', models.CharField(max_length=32, verbose_name='BANK编号')),
                ('banktype', models.SmallIntegerField(choices=[(0, '4*4'), (1, '4*5'), (2, '3*6')])),
                ('bankmark', models.SmallIntegerField(choices=[(0, '-80'), (1, '-30'), (2, '-196')])),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnum', models.CharField(max_length=32, verbose_name='BOX编号')),
                ('boxtype', models.SmallIntegerField(choices=[(0, '100'), (1, '96'), (2, '48')])),
            ],
        ),
        migrations.CreateModel(
            name='Box_pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy', models.PositiveSmallIntegerField()),
                ('bnum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ybk.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clitext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followuptext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Outlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creattime', models.TimeField(auto_created='NOW')),
                ('outlist', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Sample_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creattime', models.TimeField(auto_created='NOW')),
                ('snum', models.CharField(max_length=32, verbose_name='样本编号')),
                ('classf', models.SmallIntegerField(choices=[(0, '血清'), (1, '血浆'), (2, '组织')])),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample_pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy', models.PositiveSmallIntegerField()),
                ('tap', models.SmallIntegerField(choices=[(0, '入库'), (1, '待存'), (2, '出库')])),
                ('box_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Box')),
                ('snum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ybk.Sample_info')),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scinum', models.CharField(max_length=32)),
                ('scitext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shnum', models.CharField(max_length=32, verbose_name='SHEET编号')),
                ('sheettype', models.SmallIntegerField(choices=[(0, '4*3'), (1, '4*5'), (2, '4*8')])),
            ],
        ),
        migrations.CreateModel(
            name='Sheet_pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy', models.PositiveSmallIntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Bank')),
                ('shnum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ybk.Sheet')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creattime', models.TimeField(auto_created='NOW')),
                ('num', models.CharField(max_length=32, verbose_name='标本编号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('classf', models.SmallIntegerField(choices=[(0, '血'), (1, '尿'), (2, '组织')])),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specimen_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('blh', models.PositiveIntegerField()),
                ('kh', models.PositiveIntegerField()),
                ('fllowup', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '不详')])),
            ],
        ),
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('roles', models.ManyToManyField(blank=True, null=True, to='ybk.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='specimen_info',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='specimen_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Specimen_info'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='science',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='science',
            name='snum',
            field=models.ManyToManyField(to='ybk.Sample_info'),
        ),
        migrations.AddField(
            model_name='sample_info',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='sample_info',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Specimen'),
        ),
        migrations.AddField(
            model_name='outlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='outlist',
            name='snum',
            field=models.ManyToManyField(to='ybk.Sample_info'),
        ),
        migrations.AddField(
            model_name='followup',
            name='Fnum',
            field=models.ManyToManyField(to='ybk.Specimen'),
        ),
        migrations.AddField(
            model_name='followup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='clinical',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='clinical',
            name='num',
            field=models.ManyToManyField(to='ybk.Specimen'),
        ),
        migrations.AddField(
            model_name='box_pos',
            name='sheet_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Sheet'),
        ),
        migrations.AddField(
            model_name='box',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='bank',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
        migrations.AddField(
            model_name='apply',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybk.Userlist'),
        ),
    ]
