# Generated by Django 2.1 on 2018-09-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applytext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='boxtype',
            field=models.SmallIntegerField(choices=[(0, '10*10'), (1, '12*8'), (2, '6*8')]),
        ),
        migrations.AlterField(
            model_name='box_pos',
            name='xy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='clitext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='Followuptext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample_info',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample_pos',
            name='xy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='scitext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_pos',
            name='xy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen_info',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen_info',
            name='blh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen_info',
            name='kh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
