# Generated by Django 2.1 on 2018-09-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0002_auto_20180909_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name_plural': '申请单'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name_plural': 'BANK信息'},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'BOX信息'},
        ),
        migrations.AlterModelOptions(
            name='box_pos',
            options={'verbose_name_plural': 'BOX位置'},
        ),
        migrations.AlterModelOptions(
            name='clinical',
            options={'verbose_name_plural': '医疗记录'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'verbose_name_plural': '随访记录'},
        ),
        migrations.AlterModelOptions(
            name='outlist',
            options={'verbose_name_plural': '出库单'},
        ),
        migrations.AlterModelOptions(
            name='sample_info',
            options={'verbose_name_plural': '样本信息'},
        ),
        migrations.AlterModelOptions(
            name='sample_pos',
            options={'verbose_name_plural': '样本位置'},
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name_plural': '科研记录'},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'verbose_name_plural': 'SHEET信息'},
        ),
        migrations.AlterModelOptions(
            name='sheet_pos',
            options={'verbose_name_plural': 'SHEET位置'},
        ),
        migrations.AlterModelOptions(
            name='specimen',
            options={'verbose_name_plural': '标本编号'},
        ),
        migrations.AlterModelOptions(
            name='specimen_info',
            options={'verbose_name_plural': '标本信息'},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='Rolename',
        ),
    ]
