# Generated by Django 2.1.1 on 2018-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0004_auto_20180921_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box_pos',
            old_name='bnum',
            new_name='boxnum',
        ),
    ]
