# Generated by Django 2.1 on 2018-10-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0005_auto_20180921_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='specimen_state',
            field=models.SmallIntegerField(choices=[(0, '登记'), (1, '待分装'), (2, '已分装')], default=0),
            preserve_default=False,
        ),
    ]
