# Generated by Django 2.1.1 on 2018-10-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0008_auto_20181019_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='creattime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outlist',
            name='creattime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sample_info',
            name='classf',
            field=models.SmallIntegerField(choices=[(0, '全血'), (1, '尿'), (2, '精子'), (3, '精浆'), (5, '颗粒细胞'), (4, '卵泡液'), (6, '血清'), (7, '血浆'), (8, '白细胞'), (9, '血细胞'), (10, '胎盘'), (11, '脐带'), (12, '毛发')]),
        ),
        migrations.AlterField(
            model_name='sample_info',
            name='creattime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='creattime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
