# Generated by Django 2.1 on 2018-10-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0009_auto_20181021_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_info',
            name='fenshu',
            field=models.IntegerField(blank=True, null=True, verbose_name='份数号'),
        ),
    ]
