# Generated by Django 2.1 on 2018-10-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybk', '0010_sample_info_fenshu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_pos',
            name='tap',
        ),
        migrations.AddField(
            model_name='sample_info',
            name='tap',
            field=models.SmallIntegerField(choices=[(0, '入库'), (1, '待存'), (2, '出库'), (3, '入盒')], default=0),
            preserve_default=False,
        ),
    ]
